# Generated by Django 3.2.24 on 2024-02-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter_type', models.CharField(choices=[('уведомление', 'уведомление'), ('платеж', 'платеж')], max_length=20, verbose_name='Направление')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема')),
                ('created_at', models.DateTimeField(verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(verbose_name='Текст')),
                ('footer_text', models.TextField(verbose_name='Текст подвала')),
            ],
        ),
    ]
