# Generated by Django 3.2.24 on 2024-02-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='letter',
            options={'verbose_name': 'Уведомление', 'verbose_name_plural': 'Уведомления'},
        ),
        migrations.AddField(
            model_name='letter',
            name='obtained_at',
            field=models.DateTimeField(null=True, verbose_name='Дата вручения'),
        ),
        migrations.AlterField(
            model_name='letter',
            name='letter_type',
            field=models.CharField(choices=[('Госпочта', 'Госпочта'), ('Платеж', 'Платеж')], max_length=20, verbose_name='Направление'),
        ),
    ]
