# Generated by Django 3.2.24 on 2024-02-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20240211_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Задолженность')),
            ],
            options={
                'verbose_name': 'Задолженность',
                'verbose_name_plural': 'Задолженность',
            },
        ),
    ]
