# Generated by Django 3.2.24 on 2024-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='debt_sum',
            field=models.FloatField(default=0, verbose_name='Сумма задолженности'),
        ),
    ]
